// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcc3NcgeIt5q7R8wEXZhLrkWagJv-J9as',
    appId: '1:361818182842:web:59feca1827885fe6f29e83',
    messagingSenderId: '361818182842',
    projectId: 'morenitapp-90cc3',
    authDomain: 'morenitapp-90cc3.firebaseapp.com',
    storageBucket: 'morenitapp-90cc3.firebasestorage.app',
    measurementId: 'G-H5NW1459EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn2d1oZgi8e2ZFqpTPbIJeCVPUcs51UHI',
    appId: '1:361818182842:android:1b33b7955b8e1a3ef29e83',
    messagingSenderId: '361818182842',
    projectId: 'morenitapp-90cc3',
    storageBucket: 'morenitapp-90cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ5SN1uPoTudnDGMVdbNfhlpnxiCHzYxU',
    appId: '1:361818182842:ios:b6612f8fc85cea39f29e83',
    messagingSenderId: '361818182842',
    projectId: 'morenitapp-90cc3',
    storageBucket: 'morenitapp-90cc3.firebasestorage.app',
    iosBundleId: 'com.example.morenitapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ5SN1uPoTudnDGMVdbNfhlpnxiCHzYxU',
    appId: '1:361818182842:ios:b6612f8fc85cea39f29e83',
    messagingSenderId: '361818182842',
    projectId: 'morenitapp-90cc3',
    storageBucket: 'morenitapp-90cc3.firebasestorage.app',
    iosBundleId: 'com.example.morenitapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcc3NcgeIt5q7R8wEXZhLrkWagJv-J9as',
    appId: '1:361818182842:web:5343a90585839dfdf29e83',
    messagingSenderId: '361818182842',
    projectId: 'morenitapp-90cc3',
    authDomain: 'morenitapp-90cc3.firebaseapp.com',
    storageBucket: 'morenitapp-90cc3.firebasestorage.app',
    measurementId: 'G-WGGPD38XB4',
  );
}
