from . import hermano
from . import banco
from . import calle
from . import localidad
from . import provincia
from . import rol
from . import usuario
from . import autoridad
from . import tipoautoridad
from . import cargo
from . import tipocargo
from . import evento
from . import tipoevento
from . import organizador
from . import cofradia
from . import proveedor
from . import grupoproveedor
from . import codigopostal
from . import libro
from . import libroanunciante
from . import grupos_permisos
from . import grupoUsuarios
